ame: 'my first container action'
description: 'Testing Github-Action For Containers'
author: 'Saurav Srivastav'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Testing! Testing! Testing!'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
